### PR TITLE
Cocoa port

### PR DESCRIPTION
**Pull request by Frityet**
this PR will eventually have a full port to Cocoa, the native GUI library for MacOS.

### CODE REVIEW

**Comment by Frityet** [comment]
@AndroGR I need some help adding Cocoa to the CMakeLists.txt, I am not used to cmake

**Comment by AndroGR** [comment]
Hello,
These days I'm not getting on my computer due to school and being sick. So while I'll be able to see your progress, I can't (temporarily) make any code commits or test anything out.

In the meantime, if you have any questions, feel free to make them; I'm able to help at any moment.

**Comment by Frityet** [comment]
> if you have any questions, feel free to make them

How do I add a new target to the cmake? in my testing this seems to completley not work as when I try to build it only goes to GTK4

**Comment by AndroGR** [comment]
You seem to have confused what previously written code (Specifically the `WIN32_TARGET` option) does, and that's why. Try using the Gtk3 or libadwaita parts instead. Otherwise I'll take care of it while you write the actual backend.

**Comment by Frityet** [comment]
> You seem to have confused what previously written code (Specifically the `WIN32_TARGET` option) does, and that's why. Try using the Gtk3 or libadwaita parts instead. Otherwise I'll take care of it while you write the actual backend.
> 
> ED: The `WIN32_TARGET` option is used to build a Windows library from Linux, it's just for Wine testing.

Oh okay, thank you!

**Comment by AndroGR** [comment]
Another thing I've noticed, you seem to mix Objective C and C code in one file, and then to the actual library. This is a horrible decision: It may not work between compilers due to different ABIs, may fail to build in the first place or may cause undefined behavior due to type mismatches.

If possible, create a C file where you call the functions from another, independently built library. So something like this could do:
```c
// backend/cocoa/nvdialog_file_dialog.c

void nvd_get_file_location_cocoa(...) {
    // FFI call, from your Obj-C code
    nvd_get_file_location_cocoa_REAL(...)
}
```
And implement `nvd_get_file_location_cocoa_REAL` in another file, which you're going to link as a library.

If all that sounds hard, you can try writing a Makefile to use temporarily. You can also use `extern "C"` if it helps but I'm still challenging the idea it's actually going to work.

**Comment by Frityet** [comment]
Objective C is fully ABI compatible with C, and each C function (not methods) use the C ABI. If required I will do that, but it will be the same result

**Comment by Frityet** [comment]
Screen Shot 2022-12-06 at 12 19 28

from this
```objc
#import <ObjFW/OFStdIOStream.h>

void fn(OFString *str)
{
	[OFStdOut writeLine: str];
}

int main()
{
	[OFStdOut writeLine: @"Calling!"];
	fn(@"Called!");
}

```

**Comment by Frityet** [comment]
Screen Shot 2022-12-06 at 12 36 09
Same result on linux

**Comment by AndroGR** [comment]
I'll fix the CMake script to compile, I hope you can test if it actually compiles.

**Comment by Frityet** [comment]
> I'll fix the CMake script to compile, I hope you can test if it actually compiles. ED: Made the first commits, I'll set up CI later to test automatically.

The objc code def compiles and works, for I have used it for previous projects

**Comment by Frityet** [comment]
Still trying to build for GTK4 :/

GTK 4 runs on MacOS btw

**Comment by Frityet** [comment]
> While it does, you can skip it altogether because the whole point of NvDialog is to use Cocoa in this case, or the native UI library in general on each system.

How do I make it build with cocoa though

**Comment by Frityet** [comment]
Update: figured it out!

**Comment by Frityet** [comment]
Screen Shot 2022-12-07 at 17 04 32

**Comment by AndroGR** [comment]
Looks like we've got most of the work away. However I noticed you enabled the libadwaita backend too. You need to disable it:
> How do I make it build with cocoa though
Since the previous changes I made in CMakeLists.txt, if macOS is detected it will automatically use Cocoa.

**Comment by Frityet** [comment]
@AndroGR with the exeception of "about" and notifications, the PR should be ready

**Comment by AndroGR** [comment]
Also, make sure to sync with `master`, there are some conflicts because you are using the older version of the `tests/` folder.

**Comment by Frityet** [comment]
> For the about dialog part, is there a ready to use Cocoa function?

Nope, none from what I have seen

**Comment by Frityet** [comment]
Done, ready to be merged

**Comment by Frityet** [comment]
it is done

**Comment by AndroGR** [comment]
Merging, thanks for the contribution!

**Pull request merged**
